/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package system.ui.components;

import java.awt.Font;
import javax.swing.WindowConstants;
import system.model.Patient;
import system.model.User;
import system.patterns.decorator.AuditLogDecorator;
import system.patterns.decorator.AuthorizationDecorator;
import system.patterns.decorator.PatientRecord;
import system.patterns.decorator.SimplePatientRecord;
import system.service.AuthenticationService;

/**
 *
 * @author User
 */
public class PatientDetailsDialog extends javax.swing.JDialog {
private final Patient patient;

    /**
     * Creates new form PatientDetailsDialog
     */
    public PatientDetailsDialog(java.awt.Frame parent, boolean modal, Patient patient) {
        super(parent, modal);
        initComponents();
        this.patient = patient;

        // --- Configure the Dialog ---
        setTitle("Decorator Pattern Demo");
        setLocationRelativeTo(parent);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE); // Important for dialogs

        // --- Populate Initial Info ---
        jLabel1.setText("Decorator Demo for Patient:");
        jLabel2.setText(patient.getPatientId() + " - " + patient.getName());
        jTextArea1.setFont(new Font("Monospaced", Font.PLAIN, 12));
        jTextArea1.setEditable(false);
        jTextArea1.setText("Click the 'Fetch Record' button to see the Decorator Pattern in action.\n" +
                           "The output will show the sequence of decorator wrappers and the final result.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Patient");

        jLabel2.setText("jLabel2");

        jButton1.setText("Fetch Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jTextArea1.setText(""); // Clear the text area

        User currentUser = AuthenticationService.getInstance().getLoggedInUser();
        if (currentUser == null) {
            jTextArea1.setText("ERROR: No user is logged in.");
            return;
        }

        log("--- Initiating Record Fetch ---");
        log("User: " + currentUser.getUsername() + " (Role: " + currentUser.getRole() + ")");
        log("Target Patient: " + patient.getPatientId() + "\n");

        log("--- Decorator Pattern Execution ---");
        log("1. Creating base 'SimplePatientRecord' object...");
        PatientRecord record = new SimplePatientRecord(patient.getPatientId());

        log("2. Wrapping with 'AuthorizationDecorator' to check role...");
        record = new AuthorizationDecorator(record, currentUser.getRole());

        log("3. Wrapping again with 'AuditLogDecorator' to log the access attempt...");
        record = new AuditLogDecorator(record, currentUser);
        log("\n--- Final 'record' object is now a chain of decorators ---");
        
        log("Calling getDetails() on the outermost decorator...\n");
        
        // This single call triggers the entire chain
        String finalDetails = record.getDetails();

        log("\n--- Final Output Received by UI ---");
        jTextArea1.append("\n" + finalDetails);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void log(String message) {
        jTextArea1.append(message + "\n");
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
